export const REGISTER_USER = "register_user"
export const REGISTER_USER_SUCCESSFUL = "register_user_successfull"
export const REGISTER_USER_FAILED = "register_user_failed"
export const CONFIRM_EMAIL = "confirm_email"
export const CONFIRM_EMAIL_SUCCESSFUL = "confirm_email_successful"
export const CONFIRM_EMAIL_FAILED = "confirm_email_failed"
