/* JOURNAL */
export const GET_JOURNAL = "GET_JOURNAL"
export const GET_JOURNAL_SUCCESS = "GET_JOURNAL_SUCCESS"
export const GET_JOURNAL_FAIL = "GET_JOURNAL_FAIL"

/* NOTE*/
export const GET_NOTE = "GET_NOTE"
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS"
export const GET_NOTE_FAIL = "GET_NOTE_FAIL"
export const DELETE_NOTE = "DELETE_NOTE"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"
export const POST_NOTE = "POST_NOTE"
export const POST_NOTE_SUCCESS = "POST_NOTE_SUCCESS"
export const POST_NOTE_FAIL = "POST_NOTE_FAIL"
